title: Electrical and Computer Engineering Safe Whale Tagging
logo: /shaad.png
description: This website provides a brief overview of our project and contact info for each team member.
#show_downloads: true
theme: jekyll-theme-minimal
